### ISSUE TITLE
Some way to know when drawer is open and closed

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/drawer#11]

**Comment by satya164** [comment]
How about a `this.props.navigation.isDrawerOpen()` method?

**Comment by slorber** [comment]
Hi,

We have a withNavigationFocus hoc, maybe it's worth adding withDrawerOpen? It would permit to re-render on change without needing to create subscriptions.

Also, with hooks it would be more convenient to expose this as a hook too, like useNavigationFocused() or useDrawerOpened() (with better names if possible)

**Comment by slorber** [comment]
There is already a hook for focus actually: useFocusState(), so it may be worth creating a useDrawerState().

https://github.com/react-navigation/react-navigation-hooks#usefocusstate

Also, the navigation prop has a `isFocused()` func so it's probbably still worth to also add a isDrawerOpen fn here

**Comment by satya164** [comment]
We should trigger `drawerOpen` and `drawerClose` events like we trigger `refocus` event in tabs. This will need change in `core` to remove the restriction that only `refocus` can be triggered.

**Comment by michizhou** [comment]
@satya164 I can help take care of this issue. If there is any further information you think I would need to achieve this task, feel free to let me know.

**Comment by satya164** [comment]
@michizhou we'd need to emit the events with `navigation.emit` (like we emit `refocus` here: https://github.com/react-navigation/tabs/blob/f27327cec5089b72796b393f55227e6719e029a1/src/utils/createTabNavigator.tsx#L151). There's also code in `core` which prevents any other event from being dispatched which needs to be removed: https://github.com/react-navigation/core/blob/cdc4d9192d5d3add1739cde47034050e52df70b4/src/getChildEventSubscriber.js#L187

**Comment by michizhou** [comment]
@satya164 I have made new commits for my PRs based on your suggestions and feedback. Whenever you have the chance, feel free to look them over and let me know if additional changes are warranted. Thank you again for your time.

**Comment by satya164** [comment]
@michizhou thank you!
