### ISSUE TITLE
Annoying Drawer Border on Android

### ISSUE THREAD

**Issue by binodnp** [react-navigation/drawer#110]
It appears that react navigation drawer was not tested for dark theme(s) as you can see weird border blinks in the the video below.

![react-navigation-drawer](https://user-images.githubusercontent.com/5472889/65834459-f1ec3000-e2fa-11e9-9263-77030df10c1c.gif)

Here's a code snippet to reproduce this issue:

```js
import React from 'react';
import {Text, View, StatusBar, StyleSheet, Button} from 'react-native';
import {createDrawerNavigator} from 'react-navigation-drawer';
import {createStackNavigator} from 'react-navigation-stack';
import {createAppContainer} from 'react-navigation';

const Sidebar = ({navigation}) => (
  <View style={styles.container}>
    <Text style={styles.text}>Sidebar</Text>
    <Button title="Close Sidebar" onPress={() => navigation.closeDrawer()} />
  </View>
);

const Home = ({navigation}) => {
  return (
    <View style={styles.container}>
      <Button title="Open Sidebar" onPress={() => navigation.openDrawer()} />
    </View>
  );
};

const Routes = createStackNavigator({Home: {screen: Home}}, {mode: 'card', headerMode: 'none'});

const Drawer = createDrawerNavigator(
  {DefaultRoutes: Routes},
  {
    contentComponent: Sidebar,
    drawerType: 'slide',
    drawerWidth: 300,
  },
);

const AppContainer = createAppContainer(Drawer);

const App = () => {
  return (
    <>
      <StatusBar backgroundColor="#121212" barStyle="light-content" />
      <AppContainer />
    </>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#121212',
  },
  text: {
    fontSize: 18,
    color: '#eeeeee',
    marginBottom: 14,
  },
});

export default App;
```

and a gist:

https://gist.github.com/binodnp/1f28059e6013ab17f5cb7d3867ceed8a

Is there any workaround for this?

**Comment by hoboman313** [comment]
workaround: https://github.com/react-navigation/drawer/issues/71#issuecomment-501909140

**Comment by Ubaid0x** [comment]
add overlayColor to transparent in contentComponent. 
like this

const Drawer = createDrawerNavigator(
  {DefaultRoutes: Routes},
  {
    contentComponent: Sidebar,
    drawerType: 'slide',
    drawerWidth: 300,
    overlayColor: 'transparent'
  },
);

**Comment by binodnp** [comment]
This issues is not related to #71 and therefore the workaround doesn't work.

**Comment by AAAstorga** [comment]
I fixed it by changing drawerType to `drawerType: 'back',`. At least its a quick workaround.
