### ISSUE TITLE
App crashed in release mode in react-native 0.61.2

### ISSUE THREAD

**Issue by ajaykumar97** [react-navigation/drawer#113]
I am using react-navigation-drawer in my application. App works fine in debug mode. But the app crashes in release mode as soon as I try to open the drawer with swipe gesture in Android.

Also tried by downgrading the drawer to the ``version 1.4.0`` but with no success.

Below is the link for the code repo

[Drawer Test](https://github.com/ajaykumar97/drawerTest)

```
"react-native": 0.61.2
"react-native-gesture-handler": "^1.4.1",
"react-native-reanimated": "^1.3.0",
"react-native-screens": "^2.0.0-alpha.3",
"react-navigation": "^4.0.10",
"react-navigation-drawer": "2.2.2",
"react-navigation-stack": "^1.9.3"
```

**Comment by satya164** [comment]
Can you post the stack trace?

**Comment by sergeidrondin** [comment]
@ajaykumar97 looks like it's an issue with react-native-gesture-handler, it can be solved like this: https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-537945905

**Comment by ajaykumar97** [comment]
> @ajaykumar97 looks like it's an issue with react-native-gesture-handler, it can be solved like this: [kmagiera/react-native-gesture-handler#320 (comment)](https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-537945905)

@sergeidrondin Thanks! This solved the issue.

**Comment by herio** [comment]
solved for me: 
"react-native-gesture-handler": "^1.5.0",
"react-native": "0.61.4",
