### ISSUE TITLE
toggleDrawer does not work when app is first opened

### ISSUE THREAD

**Issue by vinnyhoward** [react-navigation/drawer#116]
Both `DrawerActions.toggleDrawer()` and `navigation.toggleDrawer()` do not work when the app first opens on iOS (works just fine on Android) but when I do a manual reload, the methods I mentioned up above work just fine. When I console log the function in both scenarios (before manually reloading and after) I do get the results back. I have also tried downgrading `react-navigation-drawer` to `2.2.1` but still got the same results

Here is my function:

```
  toggleDrawer = () => {
    const {navigation} = this.props;
    console.log('DrawerActions :', DrawerActions.toggleDrawer);
    navigation.dispatch(DrawerActions.toggleDrawer());
  }
```

| Package.json     |   |
|------------------------------|--------|
| react-navigation             | 4.0.10 |
| react-native                 | 0.61.2 |
| react-native-gesture-handler | 1.4.1  |
| react-native-reanimated      | 1.3.0 |
| react-navigation-drawer      | 2.2.2  |

**Comment by pzatorski** [comment]
Hey it would be nice if you could provide runnable repo. Thanks

**Comment by vinnyhoward** [comment]
My teammate found out the issue, in my `AppNavigator` I refer to the `Dimensions` object provided by React Native to set the width of my drawer. On app start the width and height properties are set at 0 for whatever reason (it did not do this prior to upgrading the app a few days ago). When I reload the app I get the correct dimensions and so that is why the drawer worked. This is a separate issue. Thanks for the reply anyways! @pzatorski 

Code for reference

```
const ExploreNavigatorDrawer = createDrawerNavigator(
  {
    ExplorePage: {
      screen: TabNavigator,
      navigationOptions: {header: null},
    },
  },
  {
    drawerPosition: 'right',
    contentComponent: FiltersDrawer,
    drawerLockMode: 'locked-closed',
    drawerWidth: Dimensions.get('window').width * 0.9,
    swipeEnabled: false,
  }
);
```
