### ISSUE TITLE
Crash prod app after click outside drawer

### ISSUE THREAD

**Issue by TchernyavskyDaniil** [react-navigation/drawer#117]
Hi. 
After clicking this area, the prod app crashed and I don't know why, because in the dev is ok.
Some ideas? 
![image](https://user-images.githubusercontent.com/29048318/66434035-52314f00-ea2a-11e9-8f78-3b1e2164b757.png)

IOS 13 (btw same crash with Android)

**Comment by leitom** [comment]
Why close?

**Comment by StevieDominique** [comment]
If you found the answer, please provide it.

**Comment by StevieDominique** [comment]
the solution I found was to add => import 'react-native-gesture-handler'
in index.js

**Comment by minpham** [comment]
> the solution I found was to add => import 'react-native-gesture-handler'
> in index.js

thank you

**Comment by umairahmad27** [comment]
You can solve this issue by adding 'react-native-gesture-handler' in index.js file

1) Open index.js file
2) Add this in line # 1: import 'react-native-gesture-handler'

Now build a new aab or apk file using:  gradlew buildRelease (for aab file) gradlew assembleRelease (for apk file)

Install it to your Android Phone. Hope so it will work.

**Comment by priyanka-Sadh** [comment]
not working for me :(
Android working fine.
Debug mode ios working fine. but not in release ipa :(

**Comment by TchernyavskyDaniil** [comment]
@leitom @StevieDominique I'm so sorry
If still relevant: https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-537945905

**Comment by steele-cjf** [comment]
@TchernyavskyDaniil  thanks，i find that it need to config `react-native-gesture-handler`；
https://reactnavigation.org/docs/en/getting-started.html#installing-dependencies-into-a-bare-react-native-project

now, it work

**Comment by kopax** [comment]
It does not close on the web, all your tips are for native, is there a way I can close the drawer when clicking on the overlay on the web please?
