### ISSUE TITLE
Can't open, close or toggle Drawer

### ISSUE THREAD

**Issue by mxmzb** [react-navigation/drawer#122]
I will try to gather more information on the reasons and maybe a replicable demo, but for now, here is a rough briefing:

Since some update (not sure if RN `0.61` or a specific version of `react-navigation` / `react-navigation-drawer`) the following methods have zero effect:

- `navigation.openDrawer()`
- `navigation.closeDrawer()`
- `navigation.toggleDrawer()`

Also dispatching the actions as these methods work internally like `navigation.dispatch(DrawerActions.openDrawer())` also doesn't work.

My current versioning:

```
├── react-navigation@4.0.10
├── react-navigation-drawer@2.2.2
├── react-navigation-stack@1.9.4
├── react-navigation-transitions@1.0.12
├── react@16.10.2
├── react-native@0.61.2
```

**Comment by mxmzb** [comment]
So I've found the root of my issue, which is that my navigator stacks inside the drawer route config have the following config:

```
...
navigationOptions: {
  drawerLockMode: "locked-closed",
},
```

However, I am pretty sure that used to just disable opening / closing the drawer with gestures, I used to toggle it programatically (by calling `navigation.toggleDrawer()` or similar). Can anyone confirm or clarify, please? Thank you! 🙏

**Comment by OzzieOrca** [comment]
Thanks for finding the cause :) I spent way too long trying to figure out what was wrong...

This really should have been mentioned as a breaking change in a changelog if it was an intended change. This seems like a regression though as the docs haven't changed and still mention gestures only: https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode. 

@satya164 was there a reason this was closed without any comments?

**Comment by latusdenis** [comment]
Hey @OzzieOrca!

What was the reason of this issue? Is it possible to `openDrawer` if `lock-closed` is set to `createDrawernavigator`?

**Comment by OzzieOrca** [comment]
It's been a while... If my memory is correct, I had a drawer with
```ts
navigationOptions: {
  drawerLockMode: "locked-closed",
},
```
and calling `openDrawer` worked fine.

I assume after upgrading react-navigation (it'd take some research to figure out which version) `openDrawer` stopped working.

It makes sense that `"locked-closed"` would block gestures but it's weird that it also blocks the programatic API. Removing `"locked-closed"` fixed things. I think our need to avoid gestures had gone away and this was fine for our use case. But if there are multiple gesture components on the screen, someone may want to prevent gestures but still open the drawer programmatically.

**Comment by latusdenis** [comment]
@OzzieOrca Thanks for a quick response! Yeah, you're right, `locked-closed` doesn't work with `openDrawer` in `react-navigation v4`. 

The workaround is to use `edgeWidth`. If `edgeWidth` is set to 0, then the drawer won't be swiped from the left. 

The problem here is, that in my case `edgeWidth` should be different for different screens. It would be quite easy to implement this if `edgeWidth` would be defined in `navigationOptions`.
Unfortunately, it's specified as a default prop and I cannot get the navigation prop to check the current screen. Maybe you know, what can be the solution?

**Comment by OzzieOrca** [comment]
Nope I have no solution for you 🙁 We were fine with re-enabling gestures as the requirements changed and we removed gestures on our main page. `edgeWidth` sounds interesting. This seems like a regression that slipped through but I assume it's probably not high priority for the react-navigation team.
