### ISSUE TITLE
[WEB] - white screen after switching screens

### ISSUE THREAD

**Issue by lovetofail** [react-navigation/drawer#127]
Using react-native-reanimated https://github.com/kmagiera/react-native-reanimated/commit/825ea8f6d2f45c1c2bbf21b8b34789d72489d247
On react-native-web, after switching between screens a few times the screen goes blank. If I resize the window - the screen turns back to normal.
The second issue is that I can drag my mouse anywhere at the screen and the drawer still pops up.
Screencast - https://imgur.com/a/hi2xn3Y
Repro - https://github.com/lovetofail/Drawer-White-Screen

**Comment by guitorioadar** [comment]
Please resolve the issue or please suggest us some way to resolve it... it's very important... thanks

**Comment by omerrhamza** [comment]
same issue
