### ISSUE TITLE
App crashes in Release apk

### ISSUE THREAD

**Issue by kumaresan-cgvak** [react-navigation/drawer#129]
The app crashes whenever I try to open the side menu in release APK after updating to the version 2.3.1. But it's working fine on debug mode.

**Comment by satya164** [comment]
https://github.com/kmagiera/react-native-gesture-handler/issues/320

**Comment by umairahmad27** [comment]
You can solve this issue by adding 'react-native-gesture-handler' in index.js file

1) Open index.js file
2) Add this in line # 1: import 'react-native-gesture-handler'

Now build a new aab or apk file using:  gradlew buildRelease (for aab file) gradlew assembleRelease (for apk file)

Install it to your Android Phone. Hope so it will work.
