### ISSUE TITLE
drawer First load blink

### ISSUE THREAD

**Issue by xuekew** [react-navigation/drawer#135]
drawer content Priority display，cause First load blink
I recorded a video, [click on me to check](https://dwz.cn/Hn5zB1l5)

demo:
my package.json
`{
  "name": "example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.3",
    "react-native-gesture-handler": "^1.5.0",
    "react-native-reanimated": "^1.3.2",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }
}`

App.js

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React from 'react';
import {Text, View} from 'react-native';
import {createAppContainer} from 'react-navigation';
import {createDrawerNavigator} from 'react-navigation-drawer';

class Hello extends React.Component {
  render() {
    return (
      <View>
        <Text>hello</Text>
      </View>
    );
  }
}

const App = createAppContainer(
  createDrawerNavigator(
    {
      Hello,
    },
    {
      drawerBackgroundColor: 'blue',
    },
  ),
);
export default App;`

**Comment by mrkrand** [comment]
Hi,

I have same issue on my app. Did you find out what causes this?

**Comment by programadorce** [comment]
Same here. how fixed ?

**Comment by mrkrand** [comment]
Probably closed because of this:
https://github.com/react-navigation/drawer/issues/108

**Comment by technoplato** [comment]
I fixed it! Nothing fancy. Just check if you're on the first drawer render. If you are, set the first render flag to false and return null.

Here's my relevant code:

**Menu Component**
```
class Menu extends React.Component {
  render() {
    // Fix initial flash when loading
    if (initialRender) {
      initialRender = false;
      return null;
    }

    const drawerItemFontSize = Device.isTablet ? 34 : 28;

    const { navigate } = this.props.navigation;

    return (
      <LinearGradient
        colors={["#4DB6AC", "#000"]}
        style={styles.linearGradient}
      >
        <DrawerNavigatorItems
          {...this.props}
          labelStyle={{ color: "#ffffff", fontSize: drawerItemFontSize }}
          onItemPress={route => {
            const name = route.route.routeName;
            if (name === "TCT Kids Live") {
              Player.playLiveStream(navigate, "5395574715001");
            } else if (name === "TCT HD Live") {
              Player.playLiveStream(navigate, "5395571489001");
            } else {
              this.props.navigation.navigate(route.route.routeName);
            }
          }}
        />
      </LinearGradient>
    );
  }
}

export default Menu;
```

**AppNavigation**
```
// Manifest of possible screens
const PrimaryNav = createDrawerNavigator(
  {
    Home: {
      screen: HomeNavigator
    },
    "TCT HD Live": {
      screen: HomeNavigator
    },
    "TCT Kids Live": {
      screen: HomeNavigator
    },
    Shows: {
      screen: ShowNavigator
    },
    "TCT Kids Schedule": {
      screen: KidsScheduleNavigator
    },
    "TCT HD Schedule": {
      screen: HDScheduleNavigator
    },
    Favorites: {
      screen: FavoritesNavigator
    },
    More: {
      screen: MoreNavigator
    }
  },
  {
    headerMode: "none",
    drawerWidth: 330,
    drawerPosition: "left",
    contentComponent: Menu
  }
);
```
