### ISSUE TITLE
Drawer not visible when this.props.navigation.openDrawer() is called.

### ISSUE THREAD

**Issue by EhtishamAli786** [react-navigation/drawer#138]
I am really obsessed. I just want to disable swipe and open drawer programatically but i dont know what i am doing wrong. I have set drawerLockMode: 'locked-closed' in drawer stack. and now i am calling this.props.navigation.openDrawer() to open, but its not opening. Please tell me what is wrong.
here is code:
const MyDrawerNavigator = createDrawerNavigator(
  {
    Authenticated: {
      screen: Authenticated,
      navigationOptions: {
        drawerLockMode: 'locked-closed',
      },
    },
  },
  {
    initialRouteName: 'Authenticated',
    contentComponent: CustomSidebarMenu,
  },
);
I am calling openDrawer() in Authenticated screen, Swipe is disabled but drawer not opening.

**Comment by hbarylskyi** [comment]
Having the same issue. I have a `contentComponent` too and `drawerLockMode: 'locked-closed'`. I'm trying to open/close the drawer programmatically with `navigation.dispatch(DrawerActions.toggleDrawer());` 

Using version 2.3.3  of the library.

**Comment by ddavydov** [comment]
Same issue, version 2.3.3

**Comment by bureyburey** [comment]
same issue here with 2.3.3 as well
disabling drawerLockMode: 'locked-closed' (defaults to 'unlocked') allows me to toggle which is good enough for now (allowing gestures as well)

see this issue: https://github.com/react-navigation/drawer/issues/144
