### ISSUE TITLE
How to detect DrawerClose in contentComponent

### ISSUE THREAD

**Issue by navneetccna** [react-navigation/drawer#24]
I have contentComponent: DrawerContainer 

In DrawerContainer i have a button now I want to check text every time drawer cloesed by user

By using following code I am able to get the DrawerClose but I don't know how to pass it to contentComponent: DrawerContainer 

const defaultGetStateForAction = DrawerStack.router.getStateForAction;

DrawerStack.router.getStateForAction = (action, state) => {
    //use 'DrawerOpen' to capture drawer open event
    if (state && action.type === 'Navigation/NAVIGATE' && action.routeName === 'DrawerClose') {
        console.log('DrawerClose')
    }
    return defaultGetStateForAction(action, state);
};

**Comment by navneetccna** [comment]
@bradbumbalough yes I want to to detect that drawer is open or closed so I can change my button text based on drawer state.

**Comment by rgoldiez** [comment]
If you can use an`Animated` value, you can upgrade to 3.3.0 after this was merged yesterday: 
https://github.com/react-navigation/react-navigation-drawer/pull/40

If you can’t use an `Animated` value, you can setup a listen on the animated value listener and set state when it’s open or closed.

**Comment by satya164** [comment]
`navigation.state.isDrawerOpen`

**Comment by erik-pena** [comment]
If you're using react-navigation 2.x, the `navigation.state.isDrawerOpen` is only available as a prop to the `DrawerNavigatorConfig.contentComponent`.  If you need a more robust way to determine if the drawer is open outside of the drawer itself, I iterated on the original post from @navneetccna and implemented a "middleware" to capture and expose the drawer state--

```ts
const DrawerNavigator:NavigationContainer = createDrawerNavigator(rootRouteConfigs, drawerNavigatorConfig);

let drawerIsOpen = false;

// Implementing a Router "middleware"
const defaultGetStateForAction = DrawerNavigator.router.getStateForAction;

// Hook into the state lifecycle for the Router
DrawerNavigator.router.getStateForAction = (action:NavigationAction, state:any) => {
  if(action.type === DrawerActions.OPEN_DRAWER) {
    drawerIsOpen = true;
  } else if(action.type === DrawerActions.CLOSE_DRAWER) {
    drawerIsOpen = false;
  }

  return defaultGetStateForAction(action, state);
}

export const isDrawerOpen = ():boolean => drawerIsOpen;
```

**Comment by navneetccna** [comment]
I used similar kind of solution but using state

```
import AppNavigation from '../Navigation/AppNavigation'

export const reducer = (state, action) => {
  const newState = AppNavigation.router.getStateForAction(action, state)
  if (state && action.type === 'Navigation/OPEN_DRAWER') {
  	newState['isDrawerOpen'] = true;
  }
  if (state && action.type === 'Navigation/CLOSE_DRAWER') {
  	newState['isDrawerOpen'] = false;
  }
  return newState || state
}
