### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by Minishlink** [react-navigation/drawer#32]
Hello,

Do you plan on supporting the web? (At least through `react-native-web`)

I see these blocking points right now:

* `react-native-gesture-handler` doesn't support `react-native-web` (is this right @kmagiera @osdnk?)
* AnimatedEvent doesn't exist in `react-native-web`

**Comment by osdnk** [comment]
Hello, 
Thank you for pinging us 🙂 
Unfortunately, RNGH has no support on web and we do not have it on our radar in the nearest future. If there's anyone who'd like to help us with rewriting native logic to JS for web usage, we would be extremely grateful. 
We'll keep informing about any progresses.

**Comment by Minishlink** [comment]
@osdnk Thanks! Would you have some hints on where to get started in order to add support for Web?

**Comment by EvanBacon** [comment]
[RNGH Web Support](https://github.com/kmagiera/react-native-gesture-handler/pull/406)

**Comment by osdnk** [comment]
landed it

**Comment by geminiyellow** [comment]
@osdnk thanks your great job.
half year later still not support web right?
the `@react-navigation/web` was released but there is so pool component.
have to copy some code from here.
hope we can use web version as soon.

**Comment by EvanBacon** [comment]
@geminiyellow this works with web. The pan gesture is still not supported but you can use it and open with a button. https://github.com/kmagiera/react-native-gesture-handler/pull/555

**Comment by kopax** [comment]
@EvanBacon I am not able to close the drawer with the pan gesture, but also I can't click on backdrop overlay to close it. Do you know if this can be solve?
