### ISSUE TITLE
Drawer Menu open when user swipe from Non-edge point of screen in RTL application (Android only)

### ISSUE THREAD

**Issue by SaeedZhiany** [react-navigation/drawer#49]
### Current Behavior
**The problem exists only on Android**
When application direction set to RTL ( I18nManager.forceRTL(true) ), drawer menu open on swiping left from any point on screen.

### Expected Behavior
Just like in LTR direction I want open drawer menu when only user swipe from  edge of screen, not any other points.
**react-navigation 2.x does not have such problem.**

### How to reproduce

I created a[ github repository,](https://github.com/SaeedZhiany/ReactNavigationSwipeBug) clone and run it, then swipe to left from middle of screen, drawer will open. to better understanding of the problem, set I18nManager.forceRTL to false from the constructor and run it again (you must reload app twice to apply new direction), then when you try to swipe from middle of screen, the drawer does not open, it only opens when you swipe from edge (expected behavior)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.1.3
| react-native     | 0.58.3
| node             | 10.15.0
| npm or yarn      | 6.7.0

**Comment by beqramo** [comment]
same here, please help

**Comment by vahidalizad** [comment]
I had the same issue then i realized i can change the edgeWidth in the drawer options to - value.
you can use -width(95) and get the width from react-native-dimension.

**Comment by SaeedZhiany** [comment]
@vahidalizad thank you for your help, however, it's better to fix issue in library level. so I still keep this issue open till repository contributors may notice this problem.
another issue has mentioned the same problem in  #51

**Comment by blueturtle13g** [comment]
> -width(95)

Thanks for your response but what you suggest is a bit ambiguous, this is the code you should use:
```
DrawerConfig:{
    drawerWidth: WIDTH*.83,
    drawerPosition: "right",
    edgeWidth: 50-WIDTH
    // 50 or whatever value you want to use as edgeWidth
};
```

**Comment by satya164** [comment]
Fixed in https://github.com/kmagiera/react-native-gesture-handler/pull/572

**Comment by satya164** [comment]
Closing since the fix has been merged in gesture-handler.
