### ISSUE TITLE
Drawer Lock Mode - Cannot disable Drawer

### ISSUE THREAD

**Issue by pablodance** [react-navigation/drawer#56]
I have tried every example and cannot get this to work - pulling my hair out with this.

This is my latest setup 

import { createAppContainer, createDrawerNavigator } from 'react-navigation';
import App from '../components/App';
import HomeView from '../components/HomeView';
import CheckIn from '../components/CheckIn';
import LoginView from '../components/LoginView';
import LrmDocs from '../components/LrmDocs';
import Rota from '../components/Rota';
import SideMenu from '../components/util/SideMenu';

const AuthStack = createDrawerNavigator({
  AppContainer: App,
  LoginViewContainer:LoginView,
});

const RootStack = createDrawerNavigator({
  Login:AuthStack,
  HomeViewContainer: HomeView,
  RotaContainer: Rota,
  CheckInContainer:CheckIn,
  LrmDocsContainer: LrmDocs,
},
{
  drawerPosition: 'right',
  contentComponent: SideMenu,
  cardStyle: { backgroundColor: '#FFFFFF'},

}
);

AuthStack.navigationOptions = () => {
  return { drawerLockMode: 'locked-closed' };
};

export default createAppContainer(createDrawerNavigator(
  {
    Root: RootStack,
  }));
// export default Navigation;

but the simulator still drags out the menu in the loginview

(the logincontainer is nested within the app container)

**Comment by pablodance** [comment]
delete

**Comment by pablodance** [comment]
Have also just tried below - still no luck...


import { createAppContainer, createDrawerNavigator, createStackNavigator } from 'react-navigation';
import App from '../components/App';
import HomeView from '../components/HomeView';
import CheckIn from '../components/CheckIn';
import LoginView from '../components/LoginView';
import LrmDocs from '../components/LrmDocs';
import Rota from '../components/Rota';
import SideMenu from '../components/util/SideMenu';

const AuthStack = createStackNavigator({
  AppContainer: App,
  LoginViewContainer:LoginView,
});


const RootStack = createDrawerNavigator({
  Login:AuthStack,
  HomeViewContainer: HomeView,
  RotaContainer: Rota,
  CheckInContainer:CheckIn,
  LrmDocsContainer: LrmDocs,
},
{
  drawerPosition: 'right',
  contentComponent: SideMenu,
  cardStyle: { backgroundColor: '#FFFFFF'},

}
);

AuthStack.navigationOptions = ({ navigation }) => {
  let drawerLockMode = 'unlocked';
  if (navigation.state.index > 0) {
    drawerLockMode = 'locked-closed';
  }

  return {
    drawerLockMode,
  };
};



export default createAppContainer(createDrawerNavigator({Root: RootStack, Auth:AuthStack}));
// export default Navigation;


I am using latest version of react native, latst xcode and latest React Nav as of today.

Please help - driving me insane - been trying to get it to work in various guises for a day now.

**Comment by pablodance** [comment]
dependecies as follows:

![image](https://user-images.githubusercontent.com/1333440/55316312-080d5680-5466-11e9-9992-2f67b7215720.png)

**Comment by Elias-Graf** [comment]
Was this solved? Because I'm having the same issue

**Comment by andresmtz98** [comment]
Any update on this?
