### ISSUE TITLE
Drawer component re-renders multiple times on each navigate

### ISSUE THREAD

**Issue by skb1129** [react-navigation/drawer#63]
My route structure contains the main stack navigator, inside which there is a drawer navigator that is linked to multiple stack navigators.

I have a custom drawer component. I have put a `console.count` statement in my drawer component.

The problem is that whenever I navigate inside any of the stack navigators, some of the drawer actions are called, and due to these, the drawer component gets re-rendered multiple times.

I have attached a screenshot of the logs show this happening.

![Screenshot 2019-04-18 at 7 37 41 PM](https://user-images.githubusercontent.com/24582791/56367721-819d9680-6213-11e9-998c-78e8c984000a.png)

**Comment by satya164** [comment]
Why is multiple re-rendering an issue?

**Comment by skb1129** [comment]
The render for drawer should not be called while transitioning to any of the nested screens. It slows down the animation process of screen transition. The screens for my main stack navigator, which doesn't have a drawer navigator, work very smoothly.

**Comment by satya164** [comment]
You can prevent re-rendering your drawer with `PureComponent`/`React.memo` if it's expensive in your case.

**Comment by skb1129** [comment]
@satya164 I am already using `PureComponent`, it does not help. The screenshots I have provided are in case of using `PureComponent`.

**Comment by satya164** [comment]
We've rewritten the navigator. Please install the new alpha and check if you're facing any issues.

**Comment by skb1129** [comment]
@satya164 Thanks for the update, I tried the new alpha version. I still see the drawer getting re-rendered twice when navigating to another route. Earlier it re-rendered 4 times so this one is an improvement. I am already using `PureComponent` for the drawer component.

**Comment by cybercoder** [comment]
Sames here,
When firing navigate on every child navigators ( Stack or Tab or etc.. ) The main Custom Navigator will render again. Also i wrapped it around ```React.memo```but still same.
