### ISSUE TITLE
Get drawerOpenProgress from screen

### ISSUE THREAD

**Issue by grifotv** [react-navigation/drawer#64]
As it's possible to get the `drawerOpenProgress` from ` DrawerLayout` children https://github.com/kmagiera/react-native-gesture-handler/blob/master/DrawerLayout.js#L454-L456 it would be great to have the same possibility with the drawer navigator.

The `_renderContent` method could receive the `drawerOpenProgress`, just like the `_renderNavigationView` method.
https://github.com/react-navigation/react-navigation-drawer/blob/master/src/views/DrawerView.tsx#L300-L302

I'd like to know if you think it's a good proposal and what would be the best way to pass the `drawerOpenProgress` to a screen. Would it be via `screenProps` or a separate prop?

**Comment by grifotv** [comment]
Relates to https://github.com/react-navigation/react-navigation-drawer/pull/40

**Comment by satya164** [comment]
We could expose the `progress` animated node with context API which the screen can access.

**Comment by grifotv** [comment]
That would be helpful!

**Comment by aravind1078** [comment]
@satya164 I would like to work on it. I understood what needs to be done but am not sure of what `context API` you mentioned means? you mean passing it as a separate prop or am i missing something?

**Comment by satya164** [comment]
we need to export a `DrawerProgressConsumer` using the React context API which the user can use to get the `progress` value inside a screen:

```js
<DrawerProgressConsumer>
  (progress => {
    // ...
  })
</DrawerProgressConsumer>
```

https://reactjs.org/docs/context.html

**Comment by aravind1078** [comment]
@satya164 okay, here is what I think in `Drawer.tsx` we can create/export the DrawerProgress using context and initialize it with this.progress and put a DrawerProgress.Provider at the top and pass the `progress={this.progress}` so that they can use like:
```
<DrawerProgress.Consumer>
  (progress => {
    // ...
  })
</DrawerProgress.Consumer>
```
correct me if am wrong..

**Comment by satya164** [comment]
yes, pretty much
