### ISSUE TITLE
Flickering line when opening drawer on Android

### ISSUE THREAD

**Issue by patrickreck** [react-navigation/drawer#71]
### Current Behavior

- What code are you running and what is happening?
```
export default createAppContainer(
  createDrawerNavigator({
      HomeScreen: HomeScreen,
    },
    {
      drawerType: 'slide',
      overlayColor: 'transparent',
      style: {backgroundColor: 'purple'},
      edgeWidth: 200,
    },
    {
      initialRouteName: 'HomeScreen',
    })
);
```

- Include a screenshot if it makes sense.
![flickerline](https://user-images.githubusercontent.com/2742100/57579328-bdd2b880-749a-11e9-8e51-9f8ba3639ff4.gif)

### Expected Behavior

- What do you expect should be happening?
I would expect the drawer to seamlessly be next to the `HomeScreen`. This is currently only the case when it's fully opened. On iOS it is working as expected.

### How to reproduce

Run this expo project on a real Android device or the Android Emulator: https://expo.io/@patrickreck/drawer-line-bug

Source code is here: https://github.com/patrickreck/react-native-drawer-line-bug

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.9.1
| react-native     | Expo 32 / RN 0.57
| node             | v10.6.0
| npm or yarn      | yarn 1.7.0

**Comment by satya164** [comment]
Can you try with the latest alpha of `react-navigation-drawer` and see if it fixes the issue for you?

**Comment by patrickreck** [comment]
Hi @satya164,
I updated to the newest alpha version, however it did not fix the line. I added the updated version to the example repo if you want to try it out: https://github.com/patrickreck/react-native-drawer-line-bug

**Comment by satya164** [comment]
You need to import `createDrawerNavigator` from `react-navigation-drawer` as well

**Comment by patrickreck** [comment]
Got it. The line is still there. I updated the repo and expo example (https://expo.io/@patrickreck/drawer-line-bug)

**Comment by patrickreck** [comment]
I solved this by adding a wrapping view with the purple background color, and configuring `drawerBackgroundColor: 'transparent'`. 

`drawerBackgroundColor` is transparent by default on iOS and should be on Android too IMO.

**Comment by hoboman313** [comment]
Why close the ticket?
This issue was present with this lib since the beginning.

**Comment by naderghanbari** [comment]
I was having the same issue on iOS with `"react-navigation-drawer": "^2.3.3"` and adding `drawerBackgroundColor: 'transparent'` made the issue disappear.
