### ISSUE TITLE
Drawer resets(opens/closes) when navigating between BottomTab Screens

### ISSUE THREAD

**Issue by clRcoDE** [react-navigation/drawer#73]
### Current Behavior

Drawer Resets (opens/closes) when navigate between BottomTabNavigator Screens
drawerLockMode not working properly
both working without mentioned problems  on react-native 0.59

### Code

```

const BottomTabNavigator = createBottomTabNavigator(
    {
        Dashboard,
        Transactions,
        Transfer,
    }
)
const DrawerNavigator= createDrawerNavigator(
    {
        BottomTabNavigator,
        About,
        Setting
    },
{
 navigationOptions: ({ navigation }) => {
            return {
             drawerLockMode: 'locked-closed'
 
         }
   }
}
)
const LoginStack = createStackNavigator(
    {
        Signin,
        Signup,
        Forget
    }
)

const RootSwitch = createSwitchNavigator(
    {
        LoginStack ,
        DrawerNavigator,
    }
)

export default  AppContainer = createAppContainer(RootSwitch) 


```
### GIF
![GIF](https://user-images.githubusercontent.com/45456252/56500623-d9444680-6520-11e9-82d4-0399658707d4.gif)

### Expected Behavior

drawer behave as expected before
lock drawer on certain screens

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |  3.8.1
| react-native     | 0.55.4
| node             |  10.14.2
| npm or yarn      | 6.4.1  - 1.12.3
| react-native-gesture-handler |  1.0.5

**Comment by satya164** [comment]
Can you try the latest alpha of `react-navigation-drawer` and see if it still happens?

**Comment by unnamed92** [comment]
+1 here.

**Comment by clRcoDE** [comment]
> Can you try the latest alpha of `react-navigation-drawer` and see if it still happens?

tried but not working yet

i just followed instructions in react-navigation-drawer and its gave me build error on

 windows : run-android mode

```yarn add react-navigation-drawer```
```yarn add react-native-reanimated```
```react-native link react-native-reanimated```

(react-native-gesture-handler installed and linked before)
  
![builderror](https://user-images.githubusercontent.com/45456252/61032760-4ad0ba00-a3d7-11e9-83b1-1346f4b2e2f1.png)

my package.json dependencies

| software         | version
| ---------------- | -------
| react | 16.3.1
| react-navigation |  ^3.8.1
| react-native     | 0.55.4
| node             |  10.14.2
| npm or yarn      | 6.4.1  - 1.12.3
| react-native-gesture-handler |  1.0.5
|react-native-reanimated |^1.1.0
|react-navigation-drawer |^2.0.0

just check react-native version of issue for sure
maybe react-navigation-drawer or react-native-reanimated is not compatible with react-native 0.55.4

**Comment by clRcoDE** [comment]
changed implementaion to compile (react-native 0.55.4 supports compile ) 
but still it has build errors in react-native-reanimated and react-navigation drawer

**Comment by clRcoDE** [comment]
the problem has been fixed by changing react-navigation-drawer version to @1.0.5
