### ISSUE TITLE
No way to access active route in drawer navigator

### ISSUE THREAD

**Issue by albullington** [react-navigation/drawer#83]
I have a drawer navigator which is nested within a stack navigator. I'm using a custom component for the drawer. Currently, when a user is on a route within the drawer navigator and they click on the corresponding menu item (say, they're on the About Screen and they click on the About route in the drawer), the menu stays open.

I'd like to be able to detect which route they are currently on so that I can toggle the drawer closed if they are already on that route. 

I've tried a few different ways of accessing the route, including the new hooks library `const { routeName } = useNavigationState();` and the `activeItemKey` parameter. However, the routeName / activeItemKey always shows up as the top level item in my drawer navigator, rather than the active route.

```
const DrawerNavigatorConfig = {
  contentComponent: SideMenu,
  headerMode: "none"
};

const MenuDrawerNav = createDrawerNavigator( {
  Main: {
    screen: MainStack
  },
  Achievements: {
    screen: AchievementsScreen
  },
  Challenges: {
    screen: ChallengeScreen
  },
  MyObservations: {
    screen: MyObservations
  },
  iNatStats: {
    screen: iNatStatsScreen
  },
  About: {
    screen: AboutScreen
  }
}, DrawerNavigatorConfig );

const RootStack = createStackNavigator( {
  Home: {
    screen: SplashScreen
  },
  Onboarding: {
    screen: OnboardingScreen
  },
  Login: {
    screen: LoginStack
  },
  Main: {
    screen: MenuDrawerNav
  }
}, StackNavigatorConfig );
```

So when I'm in the SideMenu, click on About, then navigate the user to `navigation.navigate( "About )`, the routeName continues to show up as "Main". 

I should be able to detect the current, active route from within the SideMenu.

**Comment by satya164** [comment]
```js
const { state } = navigation.dangerouslyGetParent();

const activeRoute = state.routes[state.index];
```

**Comment by albullington** [comment]
Hi @satya164, I tried the code you wrote above. Unfortunately, even `dangerouslyGetParent` returns `routeName: "Main"` and `key: "id-1571252060989-2"` no matter which screen I navigate to within the drawer menu.

Here's the output of `activeRoute` from each drawer screen. The only difference is whether `isDrawerOpen` is set to true or false.
 
```
        "index": 0,
        "isDrawerOpen": false,
        "isTransitioning": false,
        "key": "id-1571252060989-2", 
        "params":undefined,
         "routeName":"Main",
         "routes":[ 
            Array
         ]
      },
      { 
         "key":"Achievements",
         "params":undefined,
         "routeName":"Achievements"
      },
      { 
         "key":"Challenges",
         "params":undefined,
         "routeName":"Challenges"
      },
      { 
         "key":"MyObservations",
         "params":undefined,
         "routeName":"MyObservations"
      },
      { 
         "key":"iNatStats",
         "params":undefined,
         "routeName":"iNatStats"
      },
      { 
         "key":"About",
         "params":undefined,
         "routeName":"About"
      }
   ]
}
```

**Comment by satya164** [comment]
Sorry that was for screens. Inside your custom component, you use `props.items.find(it => it.key === props.activeItemKey)`. That's what the default sidebar uses internally, so it definitely works.
