### ISSUE TITLE
Dynamically change the value of drawerPosition for rtl and lrt

### ISSUE THREAD

**Issue by profecialinks** [react-navigation/drawer#87]
i Have index file where all stack navigator drawer navigator are declare which gets call only once when i run app for first time, on login screen when i change toggle lang change button and login into app , drawerPosition  will not getting change , how i supposed to do that , is there any thing i missing?

**Comment by satya164** [comment]
You need to restart the app for RTL related changes to take place.

**Comment by profecialinks** [comment]
yes after restart drawer position get change but that's not the real time scenario , it have to change on language toggle

**Comment by satya164** [comment]
That's how native apps work too. You need to restart the app when user toggles the language.
