### ISSUE TITLE
Swiping the drawer is not working on RN v0.60.4

### ISSUE THREAD

**Issue by voxspox** [react-navigation/drawer#91]
Can not open drawer by swiping from left side of screen. 

also reported here: https://github.com/react-navigation/react-navigation/issues/6176

**Comment by voxspox** [comment]
{
    "react-native": "0.60.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-reanimated": "^1.2.0",
    "react-navigation": "^3.11.1",
    "react-navigation-drawer": "^2.0.0",
}

**Comment by voxspox** [comment]
it seems no gesture is recognized. Swiping does not open nor closing the drawer and additionally tapping outside the opened drawer does not close the drawer.

**Comment by Abhishekkumarshakya** [comment]
https://github.com/react-navigation/react-navigation/issues/6176#issuecomment-522956470

Swiping the drawer is working

**Comment by voxspox** [comment]
works for me
